"""add address and payment_method to orders

Revision ID: 089bf1bcd1c2
Revises: fd43902583f8
Create Date: 2025-09-10 18:23:07.485850

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "089bf1bcd1c2"
down_revision = "fd43902583f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(length=255), nullable=False))
        batch_op.add_column(
            sa.Column("payment_method", sa.String(length=50), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("payment_method")
        batch_op.drop_column("address")

    # ### end Alembic commands ###
