"""empty message

Revision ID: 25e2d1e38e70
Revises: 96ba6ef65a57
Create Date: 2025-09-30 17:11:22.696643

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "25e2d1e38e70"
down_revision = "96ba6ef65a57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("direccion", sa.String(length=200), nullable=True)
        )
        batch_op.add_column(
            sa.Column("codigo_postal", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("region", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("foto", sa.String(length=200), nullable=True))
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=False,
            existing_server_default=sa.text("now()"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(timezone=True),
            type_=postgresql.TIMESTAMP(),
            existing_nullable=False,
            existing_server_default=sa.text("now()"),
        )
        batch_op.drop_column("foto")
        batch_op.drop_column("region")
        batch_op.drop_column("codigo_postal")
        batch_op.drop_column("direccion")

    # ### end Alembic commands ###
