"""fix created_at default

Revision ID: 3f4c14f7d7e1
Revises: f3ae91314b6e
Create Date: 2025-09-17 19:02:34.808803

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f4c14f7d7e1"
down_revision = "f3ae91314b6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "payment_method", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        # 👇 FIX: set default NOW() for created_at
        batch_op.alter_column(
            "created_at",
            server_default=sa.text("NOW()"),
            existing_type=sa.DateTime(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            server_default=None,
            existing_type=sa.DateTime(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "payment_method", existing_type=sa.VARCHAR(length=50), nullable=True
        )
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # ### end Alembic commands ###
