"""add created_at to users

Revision ID: 96ba6ef65a57
Revises: 0343a8f2b69a
Create Date: 2025-09-28 16:03:42.936745

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96ba6ef65a57"
down_revision = "0343a8f2b69a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("NOW()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
