"""update users table with password_hash

Revision ID: f3ae91314b6e
Revises: 089bf1bcd1c2
Create Date: 2025-09-15 15:47:40.987232

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3ae91314b6e"
down_revision = "089bf1bcd1c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "payment_method", existing_type=sa.VARCHAR(length=50), nullable=True
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.VARCHAR(length=60), nullable=False)
        )
        batch_op.add_column(sa.Column("role", sa.String(length=50), nullable=False))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "password", sa.VARCHAR(length=60), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("role")
        batch_op.drop_column("password_hash")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "payment_method", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        batch_op.alter_column(
            "address", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###
